@url_dev=http://localhost:3055/v1/api

## SignUP
POST {{url_dev}}/signup
Content-Type: application/json
x-api-key: 0743d5b6e52aaed491fcaa58e98113588ab6dfad333b6abc5a3d45e6647578d5a8796d003d323370f1bec444e6a0650de9f824e562d462c6fe9d7bf583f796de

{
    "name": "Dat 01",
    "email": "dathoan1236234@gmail.com",
    "password": "123456",
    "factoryName": "nha may 03",
    "location": "126 Hoang Quoc Viet"
}
